# CircleCI 2.1 configuration file
#
version: 2.1
commands:
  compile:
    parameters:
      target:
        type: string
      profile:
        type: string
    steps:
      - run: |
          cd mbed-os-example-atecc608a/atecc608a
          mbed compile -t GCC_ARM -m <<parameters.target>> --profile <<parameters.profile>>
jobs:
  build:
    docker:
      - image: mbedos/mbed-os-env:latest
    working_directory: ~
    steps:
      - checkout:
          path: mbed-os-example-atecc608a
      - run: |
          cd mbed-os-example-atecc608a/atecc608a
          mbed-tools deploy
      - compile:
          target: "K64F"
          profile: "develop"
      - compile:
          target: "K64F"
          profile: "debug"
      - compile:
          target: "K64F"
          profile: "release"
      - compile:
          target: "NRF52_DK"
          profile: "develop"
      - compile:
          target: "NRF52_DK"
          profile: "debug"
      - compile:
          target: "NRF52_DK"
          profile: "release"
